server:
  port: 8081
  error:
    path: /error
spring:
  application:
    name: dvdrental
  datasource:
    url: jdbc:postgresql://localhost:5433/dvdrental
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update),production set to none or comment it
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  thymeleaf:
    cache: false
    enabled: true
    prefix:
      classpath: /templates/
    suffix: .html